/// Generated by AssetsRefGenerator on 2021/08/22
class Res {
  static const String btc_icon = "assets/images/btc_icon.png";
  static const String btch_icon = "assets/images/btch_icon.png";
  static const String eth_icon = "assets/images/eth_icon.png";
  static const String svg_dialog_bck = "assets/svgs/svg_dialog_bck.svg";
}
